## Runtime surface POI for a data-defined cave entrance.
## The node carries only stable identity/content metadata; cave geometry is
## generated by CaveSpaceGenerator when the player enters it.
class_name CaveEntrance
extends Node2D

signal entered(entrance: CaveEntrance)

var cave_id: String = ""
var cave_type_id: String = ""
var entrance_tile: Vector2i = Vector2i.ZERO
var source_biome_id: String = ""

func setup(candidate: Dictionary) -> void:
	cave_id = str(candidate.get("cave_id", ""))
	cave_type_id = str(candidate.get("cave_type_id", ""))
	entrance_tile = Vector2i(int(candidate.get("x", 0)), int(candidate.get("y", 0)))
	source_biome_id = str(candidate.get("biome", ""))
	queue_redraw()

func interact() -> void:
	entered.emit(self)

func _draw() -> void:
	# A deliberately simple placeholder: content art can replace this node later
	# without changing identity, placement, or cave-generation code.
	draw_circle(Vector2.ZERO, 14.0, Color(0.12, 0.10, 0.09, 1.0))
	draw_arc(Vector2.ZERO, 15.0, PI, TAU, 12, Color(0.48, 0.42, 0.35, 1.0), 3.0)
	draw_circle(Vector2(0, 3), 7.0, Color(0.02, 0.02, 0.025, 1.0))
