## Mechanically assembles PixelLab source PNGs into Wildfall's texture-pack
## contracts. It never generates, paints, or substitutes artwork.
##
## Usage:
## godot --headless --path . --script tools/build_pixellab_comparison_pack.gd -- <input-dir> <pack-dir>
##
## Input cells are named <section>/<index>.png. Sections: ground, terrain,
## water, resources, details, stations, parts, utilities, forage, creatures,
## creature_move. Character sheets/actions are assembled by build_character_pack.gd.
extends SceneTree

const GROUND := ["water", "sand", "grass", "forest", "dirt", "stone", "snow", "mud"]

func _init() -> void:
	var args := OS.get_cmdline_user_args()
	if args.size() != 2:
		_fail("Expected <input-dir> and <pack-dir> arguments.")
		return
	var source := args[0]
	var pack := args[1]
	for index in range(GROUND.size()):
		_write_ground(_image(source.path_join("ground/%d.png" % index)), pack.path_join("assets/ground/%s.png" % GROUND[index]))
	_write_grid(source.path_join("terrain"), pack.path_join("assets/tiles/wildfall-terrain-atlas.png"), 4, 2, 32)
	_write_grid(source.path_join("water"), pack.path_join("assets/tiles/wildfall-water-animation.png"), 4, 1, 32)
	_write_grid(source.path_join("resources"), pack.path_join("assets/tiles/wildfall-resources-atlas.png"), 4, 2, 32)
	_write_grid(source.path_join("details"), pack.path_join("assets/tiles/wildfall-ground-details.png"), 4, 2, 32)
	_write_grid(source.path_join("stations"), pack.path_join("assets/tiles/wildfall-crafting-stations.png"), 4, 1, 32)
	_write_grid(source.path_join("parts"), pack.path_join("assets/tiles/wildfall-building-parts.png"), 2, 9, 32)
	_write_grid(source.path_join("utilities"), pack.path_join("assets/tiles/wildfall-building-utilities.png"), 5, 1, 32)
	_write_grid(source.path_join("forage"), pack.path_join("assets/resources/wildfall-forage-plants.png"), 2, 2, 32)
	_write_creatures(source, pack)
	_write_manifest(pack)
	print("PixelLab comparison pack assembled at ", pack)
	quit(0)

func _write_ground(source: Image, destination: String) -> void:
	if source == null:
		return
	# PixelLab's seamless terrain source is 128px. Preserve that frequency so
	# the world no longer reads as a stamped 32px checkerboard, then repeat it
	# into the 256px pack contract without altering its pixel art.
	source.resize(128, 128, Image.INTERPOLATE_NEAREST)
	var result := Image.create_empty(256, 256, false, Image.FORMAT_RGBA8)
	for y in range(0, 256, 128):
		for x in range(0, 256, 128):
			result.blit_rect(source, Rect2i(Vector2i.ZERO, source.get_size()), Vector2i(x, y))
	_save(result, destination)

func _write_grid(folder: String, destination: String, columns: int, rows: int, cell_size: int) -> void:
	var result := Image.create_empty(columns * cell_size, rows * cell_size, false, Image.FORMAT_RGBA8)
	result.fill(Color.TRANSPARENT)
	for index in range(columns * rows):
		var source := _image(folder.path_join("%d.png" % index))
		if source == null:
			continue
		source.resize(cell_size, cell_size, Image.INTERPOLATE_NEAREST)
		result.blit_rect(source, Rect2i(Vector2i.ZERO, source.get_size()), Vector2i(posmod(index, columns) * cell_size, (index / columns) * cell_size))
	_save(result, destination)

func _write_creatures(source_root: String, pack: String) -> void:
	const columns := 7
	const cell_size := 64
	var result := Image.create_empty(columns * cell_size, cell_size * 2, false, Image.FORMAT_RGBA8)
	result.fill(Color.TRANSPARENT)
	for index in range(columns):
		for row in range(2):
			var folder := "creature_move" if row == 1 else "creatures"
			var source := _image(source_root.path_join("%s/%d.png" % [folder, index]))
			if source == null and row == 1:
				source = _image(source_root.path_join("creatures/%d.png" % index))
			if source == null:
				continue
			source.resize(cell_size, cell_size, Image.INTERPOLATE_NEAREST)
			result.blit_rect(source, Rect2i(Vector2i.ZERO, source.get_size()), Vector2i(index * cell_size, row * cell_size))
	_save(result, pack.path_join("assets/creatures/alien-creature-roster.png"))

func _write_manifest(pack: String) -> void:
	var file := FileAccess.open(pack.path_join("manifest.json"), FileAccess.WRITE)
	if file == null:
		_fail("Could not write manifest.")
		return
	file.store_string(JSON.stringify({
		"schema": "riftwake.texture-pack",
		"schema_version": 2,
		"id": "pixellab_comparison",
		"description": "Complete comparison skin assembled solely from PixelLab-generated terrain, prop, creature, character and animation sources.",
		"source": "PixelLab MCP",
		"license_note": "PixelLab generated assets; mechanically arranged only to match Wildfall texture atlas contracts.",
		"rules": ["All visual source art was generated by PixelLab.", "Atlas placement and resizing are mechanical integration steps only."]
	}, "\t"))

func _image(path: String) -> Image:
	if not FileAccess.file_exists(path):
		return null
	var result := Image.new()
	if result.load(path) != OK or result.is_empty():
		push_warning("Could not read PixelLab source cell: %s" % path)
		return null
	if result.get_format() != Image.FORMAT_RGBA8:
		result.convert(Image.FORMAT_RGBA8)
	return result

func _save(image: Image, destination: String) -> void:
	DirAccess.make_dir_recursive_absolute(destination.get_base_dir())
	if image.save_png(destination) != OK:
		_fail("Could not write %s" % destination)

func _fail(message: String) -> void:
	push_error(message)
	quit(1)
